spring.application.name=demo_3001
server.port=3000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thegioididong}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# MoMo Configuration
momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/gw_payment/transactionProcessor
momo.return-url=http://localhost:3000/orders/momo-callback
momo.notify-url=http://localhost:3000/orders/momo-notify

# Mail Configuration (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenhuyvt639@gmail.com
spring.mail.password=mxvt hvpd awdl fvae
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true