name: Build and Deploy Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HUY }}
          password: ${{ secrets.PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: quanghuy1195/demo-app:latest  

      - name: Trigger deploy to server
        run: curl -X POST ${{ secrets.DEPLOY_URL }}
